version: "3.8"

services:
  php_apache:
    container_name: php_apache
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./App:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: db
    build:
      context: ./
      dockerfile: Dockerfile.database
    restart: always
    ports:
      - "3307:3306"
